### ISSUE TITLE
doesn't seem to work - no comments in my PR's 

### ISSUE THREAD

**Issue by acidjazz** [seriousben/go-patch-cover-action#14]
i can't seem to get this to work - here is my `.github/workflows/test.yml`

```yaml
name: test
on:
  push:
    branches-ignore:
      - staging
      - production

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: "*"
     - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - uses: actions/cache@v3
        with:
          path: ~/opensearch
          key: ${{ runner.os }}-opensearch-${{ matrix.opensearch-version }}

      - uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2.2

      - uses: actions/checkout@v3

      - name: copy over your test environment
        run: cp .env.test .env; cp .env.test ./test/.env

      - name: seed our opensearch db
        run: go run database/kev/seed.go

      - name: Run Tests
        run: |
          go test ./test/... -coverpkg ./controllers -coverprofile=coverage.out -covermode=count

      - uses: seriousben/go-patch-cover-action@v1
```

here is the output of your action:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/967369/193397435-9dfeff5b-583d-471e-8da6-64ce7d8c436d.png">

i believe i have it setup correctly?

**Comment by seriousben** [comment]
Hi @acidjazz

Could you see how it behaves if you also add the pull_request event?

```
on:
  pull_request:
  push:
    branches-ignore:
      - staging
      - production
```
