### ISSUE TITLE
matrix build example?

### ISSUE THREAD

**Issue by StevenACoffman** [seriousben/go-patch-cover-action#17]
I have a multimodule private git repository:
```
repo
+-- go.work
+-- dir1
|      +-- go.mod
+-- dir2
       +-- go.mod
```
My test GitHub action workflow has a matrix strategy:
```
    strategy:
      matrix:
        workdir:
          - "./dir1"
          - "./dir2"
```

I'm not sure how to use this github action in that context. Any ideas?
